### ISSUE TITLE
Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by Ranily57** [HiDeoo/starlight-blog#6]
### Describe the bug

This bug appear when i start the local website

### To Reproduce

1. Follow the install procedure
2. Start with `npm run dev`
3. The error just appear

### Expected behavior

I just want to add blog because we need to post update of a game in it 

### How often does this bug happen?

Every time

### Additional Context

# Here is the full error: 

error   Cannot read properties of undefined (reading 'endsWith')
  File:
    E:\VRCFR Site Web\vrcfr-creators-ts\eval at instantiateModule (file:\E:\VRCFR%20Site%20Web\vrcfr-creators-ts\node_modules\vite\dist\node\chunks\dep-df561101.js:55971:28
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at eval (eval at instantiateModule (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/vite/dist/node/chunks/dep-df561101.js:55971:28), <anonymous>:62:63)
    at AstroComponentInstance.Page [as factory] (eval at instantiateModule (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/vite/dist/node/chunks/dep-df561101.js:55971:28), <anonymous>:21:12)    
    at AstroComponentInstance.init (eval at instantiateModule (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/vite/dist/node/chunks/dep-df561101.js:55971:28), <anonymous>:32:29)
    at bufferHeadContent (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/runtime/server/render/astro/render.js:106:37)
    at async renderToReadableStream (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/runtime/server/render/astro/render.js:46:5)
    at async renderPage (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/runtime/server/render/page.js:29:12)
    at async renderPage (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/core/render/core.js:45:20)
    at async #tryRenderRoute (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/core/pipeline.js:99:18)
    at async DevPipeline.renderRoute (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/core/pipeline.js:46:20)
    at async handleRoute (file:///E:/VRCFR%20Site%20Web/vrcfr-creators-ts/node_modules/astro/dist/vite-plugin-astro-server/route.js:155:18)

**Comment by HiDeoo** [comment]
Thanks for the report 🙌 

This should now be fixed in the just published [version `0.3.1`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.3.1).

**Comment by Ranily57** [comment]
It work ! thanks for the rapid answer !
